{
    "openapi": "3.0.0",
    "info": {
        "title": "My First API",
        "version": "0.1"
    },
    "paths": {
        "/api/resource.json": {
            "get": {
                "operationId": "DocDemo::index",
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                }
            }
        }
    }
}